"use strict";

const parserTypeScriptESLint = require("@typescript-eslint/parser");
const pluginImport = require("eslint-plugin-import");
const pluginJest = require("eslint-plugin-jest");
const configPrettier = require("eslint-config-prettier/prettier");
const globals = require("globals");

module.exports = [
  { files: ["**/*.{js,jsx,cjs,mjs,ts,tsx,cts,mts}"] },
  { ignores: [".yarn", "coverage/", "dist/", "src/rules/__tests__/fixtures"] },
  {
    plugins: { import: pluginImport },
    languageOptions: {
      globals: globals.node,
    },
    rules: {
      ...configPrettier.rules,
      "import/consistent-type-specifier-style": ["error", "prefer-inline"],
      "import/default": "error",
      "import/export": "error",
      "import/first": "error",
      "import/named": "error",
      "import/namespace": "error",
      "import/no-absolute-path": "error",
      "import/no-amd": "error",
      "import/no-deprecated": "warn", // this is an in progress rule
      "import/no-duplicates": "error",
      "import/no-empty-named-blocks": "error",
      "import/no-extraneous-dependencies": "error",
      "import/no-import-module-exports": "error",
      "import/no-mutable-exports": "error",
      "import/no-named-as-default": "error",
      "import/no-named-as-default-member": "error",
      "import/no-named-default": "error",
      "import/no-relative-packages": "warn",
      "import/no-self-import": "error",
      "import/no-unresolved": "error",
      "import/no-webpack-loader-syntax": "error",
      "import/order": [
        "warn",
        {
          groups: [
            "builtin",
            ["external", "internal"],
            "parent",
            ["sibling", "index"],
          ],
        },
      ],

      "accessor-pairs": "error",
      "array-callback-return": "error",
      "block-scoped-var": "error",
      complexity: ["error", 20],
      "constructor-super": "error",
      curly: ["error", "multi-line"],
      "default-case": "error",
      "default-case-last": "error",
      "dot-notation": "error",
      "for-direction": "error",
      "func-name-matching": "error",
      "func-names": "error",
      "getter-return": ["error", { allowImplicit: true }],
      "guard-for-in": "error",
      "id-denylist": "error",
      "id-match": [
        "error",
        // camelCase, PascalCase, __filename, CONST_VALUE, stream$, $el
        "^\\$?(__)?(([A-Z]|[a-z]|[0-9]+)|([A-Z_]))*\\$?$",
      ],
      "logical-assignment-operators": "warn",
      "max-depth": ["error", 4],
      "max-lines": [
        "error",
        { max: 2500, skipBlankLines: false, skipComments: false },
      ],
      "max-nested-callbacks": ["error", 7],
      "max-params": ["error", 7],
      "max-statements-per-line": ["error", { max: 1 }],
      "new-cap": "error",
      "no-alert": "error",
      "no-array-constructor": "error",
      "no-await-in-loop": "error",
      "no-bitwise": "error",
      "no-caller": "error",
      "no-case-declarations": "error",
      "no-class-assign": "error",
      "no-compare-neg-zero": "error",
      "no-cond-assign": "error",
      "no-const-assign": "error",
      "no-constant-binary-expression": "error",
      "no-constant-condition": "error",
      "no-constructor-return": "error",
      "no-control-regex": "error",
      "no-debugger": "error",
      "no-delete-var": "error",
      "no-div-regex": "error",
      "no-dupe-args": "error",
      "no-dupe-class-members": "error",
      "no-dupe-else-if": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-duplicate-imports": "error",
      "no-empty": "error",
      "no-empty-character-class": "error",
      "no-empty-pattern": "error",
      "no-empty-static-block": "error",
      "no-eval": "error",
      "no-ex-assign": "error",
      "no-extend-native": "error",
      "no-extra-bind": "error",
      "no-extra-label": "error",
      "no-fallthrough": "error",
      "no-func-assign": "error",
      "no-global-assign": "error",
      "no-implicit-globals": "error",
      "no-implied-eval": "error",
      "no-import-assign": "error",
      "no-inner-declarations": "error",
      "no-invalid-regexp": "error",
      "no-invalid-this": "error",
      "no-irregular-whitespace": "error",
      "no-iterator": "error",
      "no-label-var": "error",
      "no-labels": "error",
      "no-lone-blocks": "error",
      "no-lonely-if": "error",
      "no-loop-func": "error",
      "no-loss-of-precision": "error",
      "no-multi-assign": "error", // it's handy, but harder to read
      "no-multi-str": "error",
      "no-negated-condition": "error",
      "no-new": "error",
      "no-new-func": "error",
      "no-new-native-nonconstructor": "error",
      "no-new-object": "error",
      "no-new-symbol": "error",
      "no-new-wrappers": "error",
      "no-nonoctal-decimal-escape": "error",
      "no-obj-calls": "error",
      "no-octal": "error",
      "no-octal-escape": "error",
      "no-proto": "error",
      "no-redeclare": "error",
      "no-regex-spaces": "error",
      "no-restricted-globals": ["error", "event", "fdescribe"],
      "no-restricted-syntax": ["error", "WithStatement"],
      "no-return-assign": "error",
      "no-return-await": "error",
      "no-script-url": "error",
      "no-self-assign": "error",
      "no-self-compare": "error",
      "no-sequences": "error",
      "no-setter-return": "error",
      "no-shadow": "error",
      "no-shadow-restricted-names": "error",
      "no-sparse-arrays": "error",
      "no-template-curly-in-string": "error",
      "no-this-before-super": "error",
      "no-throw-literal": "error",
      "no-undef": "error",
      "no-undef-init": "error",
      "no-unmodified-loop-condition": "error",
      "no-unneeded-ternary": "error",
      "no-unreachable": "error",
      "no-unreachable-loop": "error",
      "no-unsafe-finally": "error",
      "no-unsafe-negation": "error",
      "no-unsafe-optional-chaining": "error",
      "no-unused-labels": "error",
      "no-unused-private-class-members": "error",
      "no-unused-vars": [
        "error",
        {
          args: "after-used",
          argsIgnorePattern: "^_",
          ignoreRestSiblings: true,
          varsIgnorePattern: "^ignored",
        },
      ],
      "no-use-before-define": ["error", "nofunc"],
      "no-useless-backreference": "error",
      "no-useless-call": "error",
      "no-useless-catch": "error",
      "no-useless-computed-key": "error",
      "no-useless-concat": "error",
      "no-useless-constructor": "error",
      "no-useless-escape": "error",
      "no-useless-rename": "error",
      "no-useless-return": "error",
      "no-var": "error",
      "no-warning-comments": [
        "error",
        { location: "anywhere", terms: ["fixme"] },
      ],
      "object-shorthand": ["error", "properties"], // methods are optional so you can specify a name if you want
      "one-var": ["error", { initialized: "never", uninitialized: "always" }],
      "prefer-arrow-callback": [
        "error",
        { allowNamedFunctions: true, allowUnboundThis: true },
      ],
      "prefer-const": "error",
      "prefer-exponentiation-operator": "warn",
      "prefer-numeric-literals": "error",
      "prefer-object-has-own": "error",
      "prefer-object-spread": "warn",
      "prefer-rest-params": "error",
      "prefer-spread": "error",
      "prefer-template": "error",
      radix: "error",
      "require-yield": "error",
      strict: "error",
      "symbol-description": "error",
      "use-isnan": "error",
      "valid-typeof": "error",
      "vars-on-top": "error",
      yoda: "error",
    },
  },
  {
    files: ["**/__tests__/**/*.+(js|ts)?(x)", "**/*.{spec,test}.+(js|ts)?(x)"],
    plugins: { jest: pluginJest },
    languageOptions: {
      globals: pluginJest.environments.globals.globals,
    },
    rules: {
      "jest/max-nested-describe": "error",
      "jest/no-commented-out-tests": "warn",
      "jest/no-conditional-expect": "error",
      "jest/no-conditional-in-test": "error",
      "jest/no-deprecated-functions": "error",
      "jest/no-disabled-tests": "warn",
      "jest/no-done-callback": "error",
      "jest/no-export": "error",
      "jest/no-focused-tests": "error",
      "jest/no-identical-title": "error",
      "jest/no-interpolation-in-snapshots": "error",
      "jest/no-large-snapshots": ["warn", { maxSize: 300 }],
      "jest/no-mocks-import": "error",
      "jest/no-test-prefixes": "error",
      "jest/prefer-called-with": "error",
      "jest/prefer-comparison-matcher": "error",
      "jest/prefer-each": "error",
      "jest/prefer-equality-matcher": "error",
      "jest/prefer-hooks-in-order": "error",
      "jest/prefer-hooks-on-top": "error",
      "jest/prefer-mock-promise-shorthand": "error",
      "jest/prefer-snapshot-hint": "error",
      "jest/prefer-to-contain": "warn",
      "jest/prefer-to-have-length": "warn",
      "jest/prefer-todo": "warn",
      "jest/valid-describe-callback": "error",
      "jest/valid-expect": "error",
      "jest/valid-expect-in-promise": "error",
      "jest/valid-title": "warn",
    },
  },
  {
    files: ["src/__tests__/lib/rules/prefer-to-have-style.test.js"],
    rules: {
      "no-template-curly-in-string": "off",
    },
  },
  {
    files: ["**/*.ts"],
    languageOptions: { parser: parserTypeScriptESLint },
  },
  {
    files: [".*.js", "*.config.js"],
    languageOptions: {
      sourceType: "commonjs",
    },
  },
];
