name: validate
on:
  push:
    branches:
      - "+([0-9])?(.{+([0-9]),x}).x"
      - "main"
      - "next"
      - "next-major"
      - "beta"
      - "alpha"
      - "!all-contributors/**"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: lts/*
      - uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
      - run: npx prettier --check .
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: lts/*
      - uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
      - run: npm run lint
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: lts/*
      - uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
      - run: npm run regenerate-docs
      - run: |
          git diff --name-only \
            | xargs -I '{}' bash -c \
              'echo "::error file={},line=1::This needs to be regenerated by running \`npm run regenerate-docs\`" && false'
  main:
    # ignore all-contributors PRs
    if: ${{ !contains(github.head_ref, 'all-contributors') }}
    strategy:
      fail-fast: false
      matrix:
        eslint: [6, 7, 8, 9, 10]
        node: [12.x, 14.x, 16.x, 18.x, 20.x, 22.x, 24.x]
        testing-library-dom: [8, 9, 10]
        exclude:
          - eslint: 9
            node: 12.x
          - eslint: 9
            node: 14.x
          - eslint: 9
            node: 16.x
          - eslint: 10
            node: 12.x
          - eslint: 10
            node: 14.x
          - eslint: 10
            node: 16.x
          - eslint: 10
            node: 18.x
          - testing-library-dom: 9
            node: 12.x
          - testing-library-dom: 10
            node: 12.x
          - testing-library-dom: 10
            node: 14.x
          - testing-library-dom: 10
            node: 16.x
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v7

      - name: ⎔ Setup node
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node }}

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

        # see https://github.com/npm/cli/issues/7349
      - if: ${{ matrix.eslint >= 9 }}
        run: npm un @typescript-eslint/parser

      - name: Install ESLint v${{ matrix.eslint }}
        run: npm install --force eslint@${{ matrix.eslint }}

      - name: Install @testing-library/dom v${{ matrix.testing-library-dom }}
        run: npm install --force @testing-library/dom@${{ matrix.testing-library-dom }}

      - name: Install TypeScript v4
        if: ${{ matrix.node == '12.x' }}
        run: npm install --force typescript@4

      - if: ${{ matrix.eslint >= 9 }}
        run: npm install --force @typescript-eslint/parser

      - name: ▶️ Run build
        run: npm run build

      - name: ▶️ Run tests with coverage
        run: npm run test -- --coverage

      - name: ⬆️ Upload coverage report
        uses: codecov/codecov-action@v7

  release:
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for trusted publishing and npm provenance
    needs:
      - prettier
      - linting
      - docs
      - main
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'testing-library/eslint-plugin-jest-dom' &&
      contains('refs/heads/main,refs/heads/beta,refs/heads/next,refs/heads/alpha',
      github.ref) && github.event_name == 'push' }}
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v7

      - name: ⎔ Setup node
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: 🏗 Run build script
        run: npm run build

      - run: ls -asl dist

      - name: 🚀 Release
        uses: cycjimmy/semantic-release-action@v6
        with:
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'main',
              'next',
              'next-major',
              {name: 'beta', prerelease: true},
              {name: 'alpha', prerelease: true}
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
